export const copy = {
  en: {
    badge: '{city} Labor Hub',
    headline: 'Simple hiring and job matching for {city}',
    subheadline:
      'A clean customer and labour platform with Bhojpuri, Hindi, posting, matching, ratings, and chat-ready sections.',
    login: 'Login',
    signup: 'Sign Up',
    customer: 'Customer',
    labour: 'Labour',
    roleTitle: 'Choose account type',
    customerRoleBody: 'Post jobs, find skilled labour, and hire faster.',
    labourRoleBody: 'Manage profile, skills, availability, and matching jobs.',
    welcomeBack: 'Welcome back',
    createAccount: 'Create account',
    loginDescription: 'Login with only the essential details and go straight to your dashboard.',
    signupDescription: 'Register quickly and continue with the right tools for your role.',
    fullName: 'Full name',
    fullNamePlaceholder: 'Enter your full name',
    email: 'Email address',
    emailPlaceholder: 'Enter your email',
    phone: 'Phone number',
    phonePlaceholder: 'Enter your phone number',
    password: 'Password',
    passwordPlaceholder: 'Enter your password',
    submitLogin: 'Open Dashboard',
    submitSignup: 'Create Account',
    switchToLogin: 'Already have an account? Login',
    switchToSignup: 'Need an account? Create one',
    demoButton: 'Open Demo',
    back: 'Back',
    needWorkers: 'I need workers',
    offerServices: 'I offer services',
    customerRoleDescription: 'Post your project details and quickly connect with millions, helpers, electricians, plumbers, and more in your area.',
    labourRoleDescription: 'Build a strong profile for your work, highlight your skills, and get discovered by customers looking for reliable local professionals.',
    startHiring: 'Start Hiring',
    signUpWorker: 'Sign up as a worker',
    allCitiesAvailable: 'Available in {city}',
    footerBenefits: 'Live opportunities in {city} • Better worker-employer matching • Professional first impression',
    envTitle: 'Single API configuration',
    envBody: 'Set EXPO_PUBLIC_API_URL once in your .env file and keep your API calls clean.',
    missingTitle: 'Missing information',
    missingBody: 'Please fill the required fields before continuing.',
    successTitle: 'Success',
    loginSuccess: 'Login completed successfully.',
    signupSuccess: 'Signup completed successfully.',
    errorTitle: 'Request failed',
    logout: 'Logout',
    customerDashboardBadge: 'Customer Home',
    labourDashboardBadge: 'Labour Dashboard',
    hello: 'Hello',
    customerSubtitle:
      'Search labour by skill, area, and availability, then post work in a clean simple flow.',
    labourSubtitle:
      'Update skills, keep your profile neat, and browse matching jobs near {city}.',
    activeLabours: 'Available labour',
    liveJobs: 'Live jobs',
    avgRating: 'Avg rating',
    hiresToday: 'Hires today',
    matchesToday: 'Matches today',
    profileViews: 'Profile views',
    completedJobs: 'Completed jobs',
    responseRate: 'Response rate',
    filtersTitle: 'Filters',
    searchPlaceholder: 'Search by skill, name, or area',
    district: 'City / Area',
    category: 'Skill',
    availability: 'Availability',
    rating: 'Rating',
    clearFilters: 'Clear filters',
    availableLaboursTitle: 'Available labour in {city}',
    noLabours: 'No labour found for the current filters.',
    popularSkillsTitle: 'Popular skills',
    postJobTitle: 'Post a job',
    postJobOpen: 'Post Job',
    jobTitle: 'Job title',
    jobTitlePlaceholder: 'Need Raj Mistri for 2 hours',
    requiredSkill: 'Required skill',
    dateTime: 'Date and time',
    dateTimePlaceholder: 'Today, 4:00 PM',
    locationLabel: 'Location',
    locationPlaceholder: 'Motijheel, Bela, {city}...',
    description: 'Job description',
    descriptionPlaceholder: 'Write the work details clearly',
    skillLevel: 'Skill level',
    postJobButton: 'Publish Job',
    close: 'Close',
    profileTitle: 'Labour profile',
    skillsTitle: 'Skills and certifications',
    preferencesTitle: 'Availability and preferences',
    reviewsTitle: 'Ratings and reviews',
    workHistoryTitle: 'Work history',
    jobRequestsTitle: 'Posted jobs for labour',
    availableJobsTitle: 'Available jobs',
    updateSkills: 'Update Skills',
    editProfile: 'Edit Profile',
    applicantsLabel: 'Applicants',
    postedLabel: 'Posted',
    distanceLabel: 'Distance',
    hireNow: 'Hire Now',
    applyNow: 'Apply Now',
    applied: 'Applied',
    ratingLabel: 'Rating',
    save: 'Save',
    cancel: 'Cancel',
    namePlaceholder: 'Enter your name',
    titlePlaceholder: 'Enter your job title',
    profileUpdatedTitle: 'Profile Updated',
    profileUpdatedMessage: 'Your profile has been updated successfully.',
    apply: 'Apply',
    applyConfirmTitle: 'Apply for Job',
    applyConfirmMessage: 'Are you sure you want to apply for "{job}"?',
    alreadyAppliedTitle: 'Already Applied',
    alreadyAppliedMessage: 'You have already applied for this job.',
    applicationSuccessTitle: 'Application Submitted',
    applicationSuccessMessage: 'Your application has been submitted successfully.',
    applicationSubmitted: 'Application submitted for {job}',
    todayWorkButton: 'I want a job today',
    todayWorkConfirmTitle: 'Request Today Work',
    todayWorkConfirmMessage: 'Your job offer will be confirmed within 15 minutes. Continue?',
    confirm: 'Confirm',
    todayWorkSuccessTitle: 'Request Submitted',
    todayWorkSuccessMessage: 'Your today work request has been submitted.',
    todayWorkNotification: 'Today work request submitted - confirmation within 15 minutes',
    notificationsTitle: 'Notifications',
    notifyTitle: 'Notifications',
    notifyCustomer: 'Get alerts when a labour responds, job is accepted, or someone becomes available nearby.',
    notifyLabour: 'Get alerts when a new job matches your skill and preferred time.',
    focusMuzaffarpur: 'Primary area: {city}',
    focusMuzaffarpurBody:
      'The platform highlights jobs and labour around {city} first, with simple city-based filters.',
    messengerTitle: 'Chat and messages',
    messengerCustomer: 'Chat directly with labour after shortlisting or hiring.',
    messengerLabour: 'Reply to customers directly when jobs match your skill.',
    jobPostedTitle: 'Job posted',
    jobPostedBody: 'Your job is now visible for nearby labour.',
    today: 'Today',
    tomorrow: 'Tomorrow',
    specificDate: 'Specific Date',
  },
  hi: {
    badge: 'मुज़फ़्फ़रपुर श्रमिक हब',
    headline: 'मुज़फ़्फ़रपुर के लिए साफ़ और आसान हायरिंग प्लेटफ़ॉर्म',
    subheadline: 'ग्राहकों और श्रमिकों के लिए साफ़ लॉगिन, जॉब पोस्टिंग, मिलान, रेटिंग और चैट-रेडी सेक्शन।',
    login: 'लॉगिन',
    signup: 'साइनअप',
    customer: 'ग्राहक',
    labour: 'श्रमिक',
    roleTitle: 'खाता प्रकार चुनिए',
    customerRoleBody: 'जॉब पोस्ट कीजिए, कुशल श्रमिक ढूंढिए और जल्दी हायर कीजिए।',
    labourRoleBody: 'प्रोफ़ाइल, कौशल, उपलब्धता और मिलती-जुलती नौकरियाँ मैनेज कीजिए।',
    welcomeBack: 'स्वागत है वापसी पर',
    createAccount: 'खाता बनाइए',
    loginDescription: 'सिर्फ़ आवश्यक जानकारी के साथ लॉगिन कीजिए और सीधे डैशबोर्ड पर जाइए।',
    signupDescription: 'जल्दी से रजिस्टर कीजिए और अपनी भूमिका के हिसाब से टूल्स का उपयोग कीजिए।',
    fullName: 'पूरा नाम',
    fullNamePlaceholder: 'अपना पूरा नाम लिखिए',
    email: 'ईमेल',
    emailPlaceholder: 'अपना ईमेल लिखिए',
    phone: 'मोबाइल नंबर',
    phonePlaceholder: 'अपना मोबाइल नंबर लिखिए',
    password: 'पासवर्ड',
    passwordPlaceholder: 'अपना पासवर्ड लिखिए',
    submitLogin: 'डैशबोर्ड खोलिए',
    submitSignup: 'खाता बनाइए',
    switchToLogin: 'पहले से खाता है? लॉगिन कीजिए',
    switchToSignup: 'खाता नहीं है? साइनअप कीजिए',
    demoButton: 'डेमो खोलिए',
    back: 'वापस',
    needWorkers: 'मुझे श्रमिक चाहिए',
    offerServices: 'मैं सेवा दे सकता हूँ',
    customerRoleDescription: 'अपनी प्रोजेक्ट डिटेल्स पोस्ट कीजिए और जल्दी से अपने इलाके के लाखों श्रमिकों, इलेक्ट्रीशियनों, प्लंबर से जुड़िए।',
    labourRoleDescription: 'अपना काम का मजबूत प्रोफ़ाइल बनाइए, अपनी कौशल को हाइलाइट कीजिए और ग्राहकों से पहचान बनाइए।',
    startHiring: 'हायरिंग शुरू कीजिए',
    signUpWorker: 'श्रमिक के रूप में साइनअप कीजिए',
    allCitiesAvailable: 'मुज़फ़्फ़रपुर में उपलब्ध है',
    footerBenefits: 'मुज़फ़्फ़रपुर में काम के अवसर • बेहतर श्रमिक-नियोक्ता मिलान • पेशेवर पहला प्रभाव',
    envTitle: 'एकल API सेटिंग',
    envBody: 'EXPO_PUBLIC_API_URL को एक बार अपने .env फ़ाइल में सेट कीजिए और API कॉल को साफ रखिए।',
    missingTitle: 'जानकारी गायब है',
    missingBody: 'आगे बढ़ने से पहले आवश्यक फ़ील्ड भरिए।',
    successTitle: 'सफलता',
    loginSuccess: 'लॉगिन सफल हुआ।',
    signupSuccess: 'साइनअप सफल हुआ।',
    errorTitle: 'अनुरोध विफल',
    logout: 'लॉगआउट',
    customerDashboardBadge: 'ग्राहक होम',
    labourDashboardBadge: 'श्रमिक डैशबोर्ड',
    hello: 'नमस्ते',
    customerSubtitle:
      'कौशल, क्षेत्र और उपलब्धता देखकर श्रमिकों को खोजिए, फिर काम पोस्ट कीजिए और आसान तरीके से काम को मिलाइए।',
    labourSubtitle:
      'कौशल अपडेट रखिए, प्रोफ़ाइल साफ-सुथरी रखिए और मुज़फ़्फ़रपुर के आसपास की नौकरी की जानकारी हासिल कीजिए।',
    activeLabours: 'उपलब्ध श्रमिक',
    liveJobs: 'लाइव जॉब्स',
    avgRating: 'औसत रेटिंग',
    hiresToday: 'आज हायर किया गया',
    matchesToday: 'आज मिलान जॉब',
    profileViews: 'प्रोफ़ाइल दृश्य',
    completedJobs: 'पूर्ण काम',
    responseRate: 'प्रतिक्रिया दर',
    filtersTitle: 'फ़िल्टर',
    searchPlaceholder: 'कौशल, नाम या क्षेत्र से खोजिए',
    district: 'शहर / क्षेत्र',
    category: 'कौशल',
    availability: 'उपलब्धता',
    rating: 'रेटिंग',
    clearFilters: 'फ़िल्टर हटाइए',
    availableLaboursTitle: 'मुज़फ़्फ़रपुर में उपलब्ध श्रमिक',
    noLabours: 'इस फ़िल्टर पर कोई श्रमिक नहीं मिला।',
    popularSkillsTitle: 'लोकप्रिय कौशल',
    postJobTitle: 'जॉब पोस्ट कीजिए',
    postJobOpen: 'पोस्ट जॉब',
    jobTitle: 'जॉब का शीर्षक',
    jobTitlePlaceholder: '2 घंटे के लिए राज मिस्त्री चाहिए',
    requiredSkill: 'आवश्यक कौशल',
    dateTime: 'तारीख और समय',
    dateTimePlaceholder: 'आज, 4:00 बजे',
    locationLabel: 'स्थान',
    locationPlaceholder: 'मोतिजील, बेला, मुज़फ़्फ़रपुर...',
    description: 'जॉब विवरण',
    descriptionPlaceholder: 'काम के विवरण को स्पष्ट रूप से लिखिए',
    skillLevel: 'कौशल स्तर',
    postJobButton: 'जॉब प्रकाशित कीजिए',
    close: 'बंद कीजिए',
    profileTitle: 'श्रमिक प्रोफ़ाइल',
    skillsTitle: 'कौशल और प्रमाणपत्र',
    preferencesTitle: 'उपलब्धता और पसंद',
    reviewsTitle: 'रेटिंग और समीक्षा',
    workHistoryTitle: 'काम का इतिहास',
    jobRequestsTitle: 'श्रमिक के लिए पोस्ट की गई नौकरी',
    availableJobsTitle: 'उपलब्ध नौकरी',
    updateSkills: 'कौशल अपडेट कीजिए',
    editProfile: 'प्रोफ़ाइल संपादित कीजिए',
    applicantsLabel: 'आवेदक',
    postedLabel: 'पोस्टेड',
    distanceLabel: 'दूरी',
    hireNow: 'अब हायर कीजिए',
    applyNow: 'अब आवेदन कीजिए',
    applied: 'आवेदन किया गया',
    ratingLabel: 'रेटिंग',
    save: 'सहेजिए',
    cancel: 'रद्द कीजिए',
    namePlaceholder: 'अपना नाम लिखिए',
    titlePlaceholder: 'अपना जॉब शीर्षक लिखिए',
    profileUpdatedTitle: 'प्रोफ़ाइल अपडेट हो गई',
    profileUpdatedMessage: 'आपकी प्रोफ़ाइल सफलतापूर्वक अपडेट हो गई।',
    apply: 'आवेदन कीजिए',
    applyConfirmTitle: 'जॉब के लिए आवेदन करें',
    applyConfirmMessage: 'क्या आप "{job}" के लिए आवेदन करना चाहते हैं?',
    alreadyAppliedTitle: 'पहले ही आवेदन किया गया',
    alreadyAppliedMessage: 'आप पहले ही इस जॉब के लिए आवेदन कर चुके हैं।',
    applicationSuccessTitle: 'आवेदन सफल',
    applicationSuccessMessage: 'आपका आवेदन सफलतापूर्वक जमा हो गया है।',
    applicationSubmitted: '{job} के लिए आवेदन किया गया',
    todayWorkButton: 'आज का काम',
    todayWorkConfirmTitle: 'आज के काम के लिए आवेदन करें',
    todayWorkConfirmMessage: 'आपका जॉब ऑफर 15 मिनट में कंफर्म हो जाएगा। क्या आप जारी रखना चाहते हैं?',
    confirm: 'कंफर्म कीजिए',
    todayWorkSuccessTitle: 'आवेदन सफल',
    todayWorkSuccessMessage: 'आज का काम आवेदन सफलतापूर्वक जमा हो गया है।',
    todayWorkNotification: 'आज का काम आवेदन जमा - 15 मिनट में कंफर्मेशन',
    notificationsTitle: 'सूचनाएं',
    notifyTitle: 'सूचना',
    notifyCustomer: 'जब श्रमिक प्रतिक्रिया देते हैं, जॉब स्वीकार करते हैं या आस-पास श्रमिक उपलब्ध होते हैं तो आपको सूचित किया जाएगा।',
    notifyLabour: 'जब नई नौकरी आपकी कौशल और समय के साथ मेल खाती है तो आपको सूचित किया जाएगा।',
    focusMuzaffarpur: 'मुख्य क्षेत्र: मुज़फ़्फ़रपुर',
    focusMuzaffarpurBody:
      'यह प्लेटफ़ॉर्म पहले मुज़फ़्फ़रपुर के श्रमिकों और नौकरियों पर ध्यान केंद्रित करता है, जिसमें आसान शहर-आधारित फ़िल्टर होते हैं।',
    messengerTitle: 'चैट और संदेश',
    messengerCustomer: 'श्रमिक से संपर्क करने के लिए शॉर्टलिस्ट या हायर करने के बाद।',
    messengerLabour: 'जब नौकरियाँ आपकी कौशल से मेल खाती हैं तो ग्राहक से सीधे बात कीजिए।',
    jobPostedTitle: 'जॉब पोस्ट हो गई',
    jobPostedBody: 'आपकी जॉब अब आस-पास के श्रमिकों के लिए उपलब्ध है।',
    today: 'आज',
    tomorrow: 'कल',
    specificDate: 'निर्धारित तारीख',
  },
   bho: {
    badge: '{city} Labour Hub',
    headline: '{city} खातिर साफ़ अउर आसान काम-मजदूर प्लेटफॉर्म',
    subheadline:
      'Customer आ labour दुनो खातिर साफ़ login, job post, matching, rating आ chat-ready section.',
    login: 'Login',
    signup: 'Signup',
    customer: 'Customer',
    labour: 'Labour',
    roleTitle: 'Account type चुनीं',
    customerRoleBody: 'Job post करीं, हुनरमंद labour खोजीं आ फटाफट hire करीं.',
    labourRoleBody: 'Apna profile, skill, availability आ matching job sambhaliं.',
    welcomeBack: 'फेरु से स्वागत बा',
    createAccount: 'Account बनाईं',
    loginDescription: 'बस जरूरी details दीं आ सीधा dashboard पर चलीं.',
    signupDescription: 'जल्दी से register करीं आ अपना role हिसाब से tools use करीं.',
    fullName: 'पूरा नाम',
    fullNamePlaceholder: 'अपना पूरा नाम लिखीं',
    email: 'Email',
    emailPlaceholder: 'अपना email लिखीं',
    phone: 'Mobile number',
    phonePlaceholder: 'अपना mobile number लिखीं',
    password: 'Password',
    passwordPlaceholder: 'अपना password लिखीं',
    submitLogin: 'Dashboard खोलीं',
    submitSignup: 'Account बनाईं',
    switchToLogin: 'पहिले से account बा? Login करीं',
    switchToSignup: 'Account नइखे? Signup करीं',
    demoButton: 'Demo खोलीं',
    back: 'वापस',
    needWorkers: 'मोहे मजदूर चाही',
    offerServices: 'हम सेवा दे सकिते बानी',
    customerRoleDescription: 'अपना project details post करीं आ फटाफट अपने area के नए मजदूर, इलेक्ट्रीशियन, प्लंबर से जुड़ीं.',
    labourRoleDescription: 'अपना काम का मजबूत profile बनाईं, अपनी skill दिखाईं आ customer से पहचान बनाईं.',
    startHiring: 'Hiring शुरु करीं',
    signUpWorker: 'Worker के तउर पर signup करीं',
    allCitiesAvailable: '{city} में उपलब्ध बा',
    footerBenefits: '{city} में काम के मौका • अइसन worker-employer मिलान • Professional पहिली छाप',
    envTitle: 'एगो API setting',
    envBody: '.env में EXPO_PUBLIC_API_URL सेट करीं, फेर सब API call साफ रही.',
    missingTitle: 'जानकारी अधूरा बा',
    missingBody: 'आगे बढ़े से पहिले जरूरी field भर दीं.',
    successTitle: 'सफल',
    loginSuccess: 'Login सफल भइल.',
    signupSuccess: 'Signup सफल भइल.',
    errorTitle: 'Request fail भइल',
    logout: 'Logout',
    customerDashboardBadge: 'Customer Home',
    labourDashboardBadge: 'Labour Dashboard',
    hello: 'प्रणाम',
    customerSubtitle:
      'Skill, area आ availability देख के labour खोजीं, फेर आसान तरीका से job post करीं.',
    labourSubtitle:
      'Skill update राखीं, profile neat राखीं आ {city} के matching job देखीं.',
    activeLabours: 'Available labour',
    liveJobs: 'Live jobs',
    avgRating: 'Avg rating',
    hiresToday: 'आज hire',
    matchesToday: 'आज match job',
    profileViews: 'Profile views',
    completedJobs: 'पूरा काम',
    responseRate: 'Response rate',
    filtersTitle: 'Filters',
    searchPlaceholder: 'Skill, naam या area से खोजीं',
    district: 'सहर / इलाका',
    category: 'Skill',
    availability: 'उपलब्धता',
    rating: 'Rating',
    clearFilters: 'Filter हटाईं',
    availableLaboursTitle: '{city} में available labour',
    noLabours: 'एह filter पर कौनों labour ना मिलल.',
    popularSkillsTitle: 'Popular skills',
    postJobTitle: 'Job post करीं',
    postJobOpen: 'Post Job',
    jobTitle: 'Job title',
    jobTitlePlaceholder: '2 घंटा खातिर Raj Mistri चाहीं',
    requiredSkill: 'Required skill',
    dateTime: 'Date अउर time',
    dateTimePlaceholder: 'आज, 4:00 PM',
    locationLabel: 'Location',
    locationPlaceholder: 'Motijheel, Bela, {city}...',
    description: 'Job description',
    descriptionPlaceholder: 'काम के detail साफ-साफ लिखीं',
    skillLevel: 'Skill level',
    postJobButton: 'Job Publish करीं',
    close: 'बंद करीं',
    profileTitle: 'Labour profile',
    skillsTitle: 'Skills आ certification',
    preferencesTitle: 'उपलब्धता आ पसंद',
    reviewsTitle: 'Rating आ review',
    workHistoryTitle: 'काम के इतिहास',
    jobRequestsTitle: 'Labour खातिर posted job',
    availableJobsTitle: 'Available job',
    updateSkills: 'Skill Update',
    editProfile: 'Profile Edit',
    applicantsLabel: 'Applicants',
    postedLabel: 'Posted',
    distanceLabel: 'दूरी',
    hireNow: 'अभी Hire करीं',
    applyNow: 'अभी Apply करीं',
    applied: 'Apply हो गइल',
    ratingLabel: 'Rating',
    save: 'Save करीं',
    cancel: 'Cancel करीं',
    namePlaceholder: 'अपना नाम लिखीं',
    titlePlaceholder: 'अपना job title लिखीं',
    profileUpdatedTitle: 'Profile Update हो गइल',
    profileUpdatedMessage: 'रउरा profile सफलतापूर्वक update हो गइल बा.',
    apply: 'Apply करीं',
    applyConfirmTitle: 'Job खातिर Apply करीं',
    applyConfirmMessage: 'की रउवा "{job}" खातिर apply करना चाहत बानी?',
    alreadyAppliedTitle: 'पहिले ही Apply हो गइल',
    alreadyAppliedMessage: 'रउवा एह job खातिर पहिले ही apply कर चुके बानी.',
    applicationSuccessTitle: 'Application Submit हो गइल',
    applicationSuccessMessage: 'रउरा application सफलतापूर्वक submit हो गइल बा.',
    applicationSubmitted: '{job} खातिर application submit हो गइल',
    todayWorkButton: 'आज का काम',
    todayWorkConfirmTitle: 'आज का काम Request करीं',
    todayWorkConfirmMessage: 'रउरा job offer 15 मिनट में confirm हो जाई. जारी राखीं?',
    confirm: 'Confirm करीं',
    todayWorkSuccessTitle: 'Request Submit हो गइल',
    todayWorkSuccessMessage: 'रउरा आज का काम request submit हो गइल बा.',
    todayWorkNotification: 'आज का काम request submit - 15 मिनट में confirmation',
    notificationsTitle: 'Notifications',
    notifyTitle: 'Notification',
    notifyCustomer: 'जब labour जवाब दे, job accept होखे, या nearby labour available होखे त alert मिली.',
    notifyLabour: 'जब नया job रउरा skill आ time से match करी त alert मिली.',
    focusMuzaffarpur: 'मुख्य इलाका: {city}',
    focusMuzaffarpurBody: 'ई platform सबसे पहिले {city} के labour आ job पर focus करेला.',
    messengerTitle: 'Chat आ message',
    messengerCustomer: 'Shortlist या hire कइला के बाद labour से सीधा बतिआईं.',
    messengerLabour: 'Matching job मिलते customer से सीधा बात करीं.',
    jobPostedTitle: 'Job post हो गइल',
    jobPostedBody: 'रउरा job अब nearby labour लोग देख सकत बा.',
    today: 'आज',
    tomorrow: 'काल्ह',
    specificDate: 'Fix date',
  },
};
